spring:
  config:
    activate:
      on-profile:
      - prod
  application:
    name: pharmacy-gateway
server:
  port: 8080        
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/
      
---

spring:
  config:
    activate:
      on-profile:
      - test
  application:
    name: pharmacy-gateway
server:
  port: 8060        
eureka:
  client:
    enabled: false
    
---


spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: pharmacy-gateway
server:
  port: 8060        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/               